### ISSUE TITLE
Crash when starting a Windows 10 application

### ISSUE THREAD

**Issue by garfildalex6** [TiCodeX/SQLSchemaCompare#72]
Good afternoon.I have a problem launching the application. It won't start at all
Logging:
2024-11-25 21:20:59.824|18736|INFO|electron|Starting SQL Schema Compare v2024.8.1
2024-11-25 21:21:00.210|18736|INFO|electron|Starting service C:\Users\test\AppData\Local\Programs\SQL Schema Compare\bin\TiCodeX.SQLSchemaCompare.UI.exe (25436)
2024-11-25 21:22:42.671|18736|ERROR|electron|Unable to contact service (ERR_CONNECTION_REFUSED)

_Originally posted by @garfildalex6 in https://github.com/TiCodeX/SQLSchemaCompare/issues/65#issuecomment-2498857243_

**Comment by drebrez** [comment]
Hi @garfildalex6,

do you have the .NET 8 runtimes installed on your system?

Can you share the output of this command?
`dotnet --info`

**Comment by garfildalex6** [comment]
Hi, @drebrez . Thanks for your help!

Here is the output of the command:
`"dotnet" is not internal or external
command, executable program or batch file.`

**Comment by garfildalex6** [comment]
Hi, @drebrez . Thanks for your help!
Now I have installed .NET.
The application still won't launch.

Command output:
![image](https://github.com/user-attachments/assets/d8f7163f-ffb2-4f31-a9f2-57bf6fa3131f)

**Comment by drebrez** [comment]
Hi @garfildalex6,

I just tried on a fresh windows installation and figured out.

As I can see from your screenshot you installed the ".NET Desktop Runtime", for this application you also need to install the "ASP.NET Core Runtime".

You can download it from https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-aspnetcore-8.0.11-windows-x64-installer or you can install it with `winget install Microsoft.DotNet.AspNetCore.8`.

Please report back if it works after installing the correct runtimes so that I'll update the Readme to properly explain what are the requirements.

Thanks

**Comment by garfildalex6** [comment]
Hello @drebrez 

Thank you for your help. The application now starts.
Tell me, can your application work in this scenario: create a snapshot of the current schema, and later create a new snapshot and compare them so that the application generates sql code for migrating the schema?

**Comment by drebrez** [comment]
Hi @garfildalex6,

good that you also confirmed that it was actually the "ASP.NET Core Runtime" the missing dependency.

In the meantime I decided to avoid those dependencies and changed to create the installer with the self-contained dotnet application so there's no need to manually install the dependencies, I will prepare a release soon.

> Tell me, can your application work in this scenario: create a snapshot of the current schema, and later create a new snapshot and compare them so that the application generates sql code for migrating the schema?

You mean if it's able to compare the snapshots? 
I'm not sure, I never tried to connect directly to a snapshot, but if it's possible to connect and perform queries then it should be possible to do the compare and generate the sql code.

The project page for configuring the source/target connections is a bit limited, if you need a specific connection string I can try to implement this https://github.com/TiCodeX/SQLSchemaCompare/issues/75 as soon as possible.

**Comment by drebrez** [comment]
@garfildalex6 FYI: I've released a new version (2024.12.1) that should fix the dotnet runtime dependency problem, with this version there's no need to install the runtime in the system as it's provided within the application.

**Comment by garfildalex6** [comment]
Hello, @drebrez. 
Yes, your new build solved the problem of installing dependencies. The application starts without installing additional programs.
Thank you for your promptness!

**Comment by garfildalex6** [comment]
> You mean if it's able to compare the snapshots?
I'm not sure, I never tried to connect directly to a snapshot, but if it's possible to connect and perform queries then it should be possible to do the compare and generate the sql code.

Now in your interface I see that there must be two databases. But I'm talking about snapshots of one database, for example, a snapshot of the schema could be saved to a file, and later, after changes to the database, I could compare the current version with the previous version of the schema (snapshot), and your application would generate sql to migrate the changes. 
@drebrez , Do you understand what I'm talking about?

**Comment by drebrez** [comment]
Hi @garfildalex6,

> Yes, your new build solved the problem of installing dependencies. The application starts without installing additional programs.

Thanks for the feedback

> But I'm talking about snapshots of one database, for example, a snapshot of the schema could be saved to a file

Now I see your use case but I have a question: 

What kind of file is the snapshot that you save? it's a special snapshot file or you mean the whole sql script of the schema?

**Comment by garfildalex6** [comment]
Hi, @drebrez 
> What kind of file is the snapshot that you save? it's a special snapshot file or you mean the whole sql script of the schema?

Rather, everything here depends on the developer’s approach. I have seen that some programs use special files, for example, xml, which saves the structure of the circuit, as well as other necessary properties. Someone saves the necessary SQL scripts and then compares them. 
I took this idea from the Devart dbForge for Mysql program. They save snapshots in .sql files. In one directory there are tables in another directory with triggers. In the future, it is possible to compare these snapshots and the program generates an sql script for migration.

**Comment by drebrez** [comment]
Hi @garfildalex6,

the idea is interesting but would need to write a parser for the sql scripts and sounds quite complex.

If you have the sql files you can re-create a temporary database and then compare that, otherwise it might be implemented directly in SQL Schema Compare with an in-memory database, but I don't know if it's possible.

If it's ok for you I'll close this issue as it was related to the crash, if you want to suggest features to add to the application, feel free to open a new issue.

Thanks
